### PR TITLE
Adding links to IGMP conformance suites for frrouting.org

### PR DESCRIPTION
**Pull request by gpnaveen**
Following links have been added.

- [PIM](/test-results/PIM_extended_results.pdf)
- [IGMPv2](/test-results/IGMPv2_extended_results.pdf)
- [IGMPv3](/test-results/IGMPv3_extended_results.pdf)
- 
Signed-off-by: naveen <nguggarigoud@vmware.com>

### CODE REVIEW

**Review by mobash-rasool — APPROVED** [review]
Looks good to me.

**Comment by pguibert6WIND** [comment]
is the path where binary stored correct ?
`static/test-results/IGMPv2_extended_results.pdf ` ?

**Comment by gpnaveen** [comment]
> is the path where binary stored correct ? `static/test-results/IGMPv2_extended_results.pdf ` ?
> 
> seem ok. how can I see the test result without waiting for this to being merged?

I just followed the existing binary file informations and appended to the list.

Actual files are already upstreamed to wiki page : https://github.com/FRRouting/frr/wiki

**Review by qlyoung — DISMISSED** [review]
These links would be broken. If you disagree, please explain exactly how those links would work.

**Pull request merged**
