### PR TITLE
Add VyOS to the list of contributors

### PR DESCRIPTION
**Pull request by dmbaturin**
We have contributed patches and testing, and we are paying for the FRR Slack. I suppose it's time to add our logo to the contributor list.

### CODE REVIEW

**Comment by Jafaral** [comment]
@dmbaturin  can you please add a signed-off-by  to your commit.

**Comment by dmbaturin** [comment]
@Jafaral Yes, sorry, I didn't notice that policy. Fixed now.

**Comment by dmbaturin** [comment]
Hmm. Is everything fine with the deployment procedure? The PR is merged, but the logo is not on the live website yet.

**Comment by dmbaturin** [comment]
@Jafaral This PR is merged, but do you plan to include it in the live version of the website? It looks like the live website was updated and rebuilt since then, but our logo still isn't there.

**Pull request merged**
