### PR TITLE
Adding Multicast conformance results.

### PR DESCRIPTION
**Pull request by gpnaveen**
Signed-off-by: Naveen <nguggarigoud@vmware.com>

### CODE REVIEW

**Review by mwinter-osr — COMMENTED** [review]
I would prefer if we could have a discussion on the results first. I've noticed that you probably mark the "inconclusive" result as "unreliable" (which I think should be marked different). Additionally, I fixed various issues in your ANVL scripts.

Would like to discuss results first before merging this

**Review by mwinter-osr — CHANGES_REQUESTED** [review]
Let's discuss the results first. See my other comment

**Review by mwinter-osr — CHANGES_REQUESTED** [review]
- IGMPv3 results seems to be the wrong PDF with old results and latest show version is 8.0
- I would prefer the "Inconclusive" fields to have a different color than "unpredictable" to make it less likely to be confused. My suggestion would be light grey background (more similar to "untested" which is white and similar to it)

**Comment by qlyoung** [comment]
@gpnaveen can you fix these or confirm if we can close this one?

**Comment by gpnaveen** [comment]
@qlyoung We are discussing with Martin, but not updating the PR. Please wait for few more days.

**Comment by gpnaveen** [comment]
> * IGMPv3 results seems to be the wrong PDF with old results and latest show version is 8.0
> * I would prefer the "Inconclusive" fields to have a different color than "unpredictable" to make it less likely to be confused. My suggestion would be light grey background (more similar to "untested" which is white and similar to it)

These changes are taken care in the latest updates to the PR.

**Review by mwinter-osr — APPROVED** [review]

**Pull request merged**
